const ProductsData = [
  {
    Id: 1,
    ProductName: "Iphone 15",
    ProductDescription: "Iphone",
    ProductCategory: "Smartphones",
    ProductPrice: 30000,
    ProductImg: "https://source.unsplash.com/random/?city,night",
    ProductBrand: "Apple",
  },

  {
    Id: 2,
    ProductName: "Iphone 14",
    ProductDescription: "Iphone",
    ProductCategory: "Smartphones",
    ProductPrice: 30000,
    ProductImg: "https://source.unsplash.com/random/?city,night",
    ProductBrand: "Apple",
  },

  {
    Id: 3,
    ProductName: "Iphone 13",
    ProductDescription: "Iphone",
    ProductCategory: "Smartphones",
    ProductPrice: 30000,
    ProductImg: "https://source.unsplash.com/random/?city,night",
    ProductBrand: "Apple",
  },

  {
    Id: 4,
    ProductName: "Iphone 12",
    ProductDescription: "Iphone",
    ProductCategory: "Smartphones",
    ProductPrice: 30000,
    ProductImg: "https://source.unsplash.com/random/?city,night",
    ProductBrand: "Apple",
  },
  {
    Id: 5,
    ProductName: "Iphone 11",
    ProductDescription: "Iphone",
    ProductCategory: "Smartphones",
    ProductPrice: 30000,
    ProductImg: "https://source.unsplash.com/random/?city,night",
    ProductBrand: "Apple",
  },

  {
    Id: 6,
    ProductName: "Samsung Galaxy S24",
    ProductDescription: "Samsung Galaxy ",
    ProductCategory: "Smartphones",
    ProductPrice: 30000,
    ProductImg: "https://source.unsplash.com/random/?city,night",
    ProductBrand: "Samsung",
  },
  {
    Id: 7,
    ProductName: "Samsung Galaxy S23",
    ProductDescription: "Samsung Galaxy ",
    ProductCategory: "Smartphones",
    ProductPrice: 45000,
    ProductImg: "https://source.unsplash.com/random/?city,night",
    ProductBrand: "Samsung",
  },
  {
    Id: 8,
    ProductName: "Samsung Galaxy S22",
    ProductDescription: "Samsung Galaxy ",
    ProductCategory: "Smartphones",
    ProductPrice: 30000,
    ProductImg: "https://source.unsplash.com/random/?city,night",
    ProductBrand: "Samsung",
  },
  {
    Id: 9,
    ProductName: "Samsung Galaxy S21",
    ProductDescription: "Samsung Galaxy ",
    ProductCategory: "Smartphones",
    ProductPrice: 30000,
    ProductImg: "https://source.unsplash.com/random/?city,night",
    ProductBrand: "Samsung",
  },
  {
    Id: 10,
    ProductName: "Samsung Galaxy S20",
    ProductDescription: "Samsung Galaxy ",
    ProductCategory: "Smartphones",
    ProductPrice: 30000,
    ProductImg: "https://source.unsplash.com/random/?city,night",
    ProductBrand: "Samsung",
  },
];

export default ProductsData;
